### ISSUE TITLE
Upgrade to version 2.2.1

### ISSUE THREAD

**Issue by ekeaton** [Trillium-Solutions/gtfs-to-html-service#13]
gtfs-to-html has upgraded to version 2.2.1 https://github.com/BlinkTagInc/gtfs-to-html due to this new change noted here https://github.com/BlinkTagInc/gtfs-to-html/issues/125

Per the G2H version update process outlined here https://github.com/Trillium-Solutions/gtfs-to-html-service/issues/8

I created a new branch on the timetables repo (2.2.1) for testing purposes. I archived all of the a-h configs since Brendan's new update included changes to the config. And I've added a sample config as well as a trillium config for testing purposes which are the newer config versions.

@anniekfifer If you have any questions let me know!

**Comment by anniekfifer** [comment]
Thank you @ekeaton ! Sorry for the delay, I've been out of the office. I will update staging with a 2.2.1 branch today and will update you here when it's ready.

**Comment by evantrillium** [comment]
@anniekfifer @ekeaton I will update configs tomorrow - they are backwards compatible - I just need to add the line he added

**Comment by anniekfifer** [comment]
@ekeaton @evantrillium Updated staging to use g2h 2.2.1! Staging is also using the "2.2.1" branch of the timetables repo so please make config changes on that branch. Those changes will be pulled into the "main" branch when production is updated to use g2h 2.2.1.

**Comment by ekeaton** [comment]
@evantrillium Have you had a chance to test staging for g2h 2.2.1?

**Comment by evantrillium** [comment]
@ekeaton I have not - I will take a look this afternoon

**Comment by evantrillium** [comment]
@anniekfifer tested and looks good on staging!

**Comment by anniekfifer** [comment]
@evantrillium @ekeaton Thank you! Everything now uses g2h 2.2.1 and the 2.2.1 branch of the timetables repo has been pulled into main

**Comment by ekeaton** [comment]
@anniekfifer Thank you!!!!
