### ISSUE TITLE
Configs/templates versioning in timetables repo

### ISSUE THREAD

**Issue by anniekfifer** [Trillium-Solutions/gtfs-to-html-service#8]
Making this issue here since it's more about coordinating g2h upgrades in gtfs-to-html-service, but this could also go in the timetables repo.

- [ ] Decide how assets will be updated and what timetables branches g2h sites will use.
- [ ] Make necessary changes and branch updates in ansible
- [ ] Document in this repo and in timetables repo README

**Comment by anniekfifer** [comment]
@ekeaton @danielleogden I've proposed a system below for branches in the [timetables repo](https://github.com/Trillium-Solutions/timetables) that I think will work well with the gtfs-to-html-service server setup for:
- Testing changes to timetable assets and new assets in a non-production environment
- Testing g2h tool upgrades without disrupting the existing production or testing environment

It's important to note that the branches in the timetable repo will be maintained by the websites team, so if anything about this setup raises any concerns about usability or maintainability or if you have any questions please let me know! Or any feedback or thoughts you have about how you'd like to maintain assets, I figured it'd be helpful to have something to start with. 

The one thing I'm not sure about how well it will work in website's workflow is having to update a `production` branch from the working branch whenever a change is deemed acceptable, as that could either be tedious if that's a common task or require cherry-picking of commits into production if not all of `main` is acceptable (you'd of course be more than welcome to organize work into separate working branches if you wanted, but I think it's best to have staging always deploy `main` outside of rare exceptions, so those could be hard to test). I don't think there's any way around that if we want to maintain a stable assets branch but lmk if you think the effort isn't worth it. 

### Timetables branches
- `main` 
  - "development/working" branch, unstable (but should not be used for testing changes related to g2h version updates)
  - Deployed to [staging-gtfstohtml](staging-gtfstohtml.trilliumtransit.com)
    - Staging will be where users can test changes to configs and templates almost* immediately (*currently updates assets every 5 minutes or can be manually triggered using this [jenkins task](https://regression-testing.trilliumtransit.com/view/gtfstohtml/job/deploy_timetables_to_gtfstohtml/))
    - Staging should always be using the same gtfs-to-html-service branch as production (`master`), so it can always serve as a reliable testing environment for changes to timetables assets
- `production`
  - production branch, stable configs/templates only
    - should be updated from `main` each time an experimental change is accepted or new config/template is finalized
  - Deployed to [production-gtfstohtml](gtfstohtml.trilliumtransit.com)
- Experimental version branches (i.e. `2.x` or `1.6.4`)
  - created for testing g2h tool version updates, will ultimately be pulled into `main` and `production`
  - When ready for testing with gtfs-to-html-service, these will be deployed to [development-gtfstohtml](development-gtfstohtml.trilliumtransit.com).
    - Development will host experimental gtfs-to-html-service code (also a versioned branch like `2.x`) for testing the g2h upgrade with the new assets.
 
### [G2H tool](https://github.com/BlinkTagInc/gtfs-to-html) version upgrade process
- Websites team opens a github issue in gtfs-to-html-service repo with the version number they want to upgrade to
- Websites team creates a new versioned branch in timetables repo and updates the github issue with the branch name when it's ready to test. 
  - The branch might be identical to `main` but it's important to test on a separate branch so changes can be tested if needed without additional steps.
- gtfs-to-html-service developer upgrades g2h in a new versioned branch and deploys to development
- Websites team tests on [development-gtfstohtml](development-gtfstohtml.trilliumtransit.com), and lets gtfs-to-html-service developer know if more changes are needed or if everything works ok. 
- When development gtfs-to-html-service is confirmed to be working with the new assets, the gtfs-to-html-service developer performs an upgrade (these things should all happen at the same time):
  - gtfs-to-html-service: version branch is pulled into `master`
  - timetables: version branch is pulled into `main`, then `main` is pulled into `production`
  - Staging and production gtfs-to-html-service are upgraded with updated code and assets
  - Version branches can be removed at this point, or kept for future use or reference if helpful
- gtfs-to-html-service developer closes github issue when upgrade is complete

**Comment by ekeaton** [comment]
@anniekfifer This makes sense! The only part I'm trying to think through is:

> production
production branch, stable configs/templates only
**should be updated from main each time an experimental change is accepted or new config/template is finalized**

Ultimately I'd like the Timetables repo to be used by the Support team. Since they will be the ones Generating Timetables from GTFSM and this process is for them. So if they are running timetables and realize one line in the config needs to be changed from  `showStopCity": false,` to `"showStopCity": true` and do so on the `Main` branch. (Which makes sense)  I'm trying to think through how they would get those changes onto the `Master` branch without needing to use the terminal etc. Maybe just then updating the `Production` branch manually with the same changes? I'll run this by Evan! Because I believe they do update Static Assets at this time for imap changes, I'm just not sure how. But I think its from editing within GH like so 
<img width="311" alt="Screen Shot 2021-08-12 at 7 56 55 AM" src="https://user-images.githubusercontent.com/43942870/129219490-64577b45-e4dd-401a-9b29-65402201c3ae.png">


But thank you for outlining all of this out!

**Comment by anniekfifer** [comment]
>Ultimately I'd like the Timetables repo to be used by the Support team.

Thank you for clarifying this!

>@anniekfifer I spoke to @evantrillium and he's come up with a solution that should resolve my question above. I believe he'll be reaching out to you soon to go over it.

Awesome, sounds great!

I'll say now that the more I think about it, having a working branch and production branch for assets is probably overkill. If most changes are going to be small config changes, we probably don't need to have a separate branch for testing changes. It'd be more convenient and not super risky to just push changes directly to production, if there are broken or un-finalized configs or templates they're unlikely to be used mistakenly. I think that's how maps assets work too, changes to assets on the main/master branch are immediately deployed to production.

>I'm trying to think through how they would get those changes onto the Master branch without needing to use the terminal etc. Maybe just then updating the Production branch manually with the same changes

To answer this question though -- edits on `main` could be made with that edit tool in github, and then a pull request would be created for pulling `main` into `production` in the github UI as well.

**Comment by evantrillium** [comment]
@anniekfifer my preference is for a small library of config files for support to choose from, and their export receipts will tell them which to use

so rather than having say, one for each agency, or one for all agencies, we'd have maybe 4-5 different ones with generic names like 'config-a' and 'config-b' and then agencies get slotted into them - we'd work to have those be the available option for future g2h clients and website clients.

how hard is it to add additional configs to the available options?

**Comment by anniekfifer** [comment]
> @anniekfifer my preference is for a small library of config files for support to choose from, and their export receipts will tell them which to use
> 
> so rather than having say, one for each agency, or one for all agencies, we'd have maybe 4-5 different ones with generic names like 'config-a' and 'config-b' and then agencies get slotted into them - we'd work to have those be the available option for future g2h clients and website clients.

Definitely, this will be a given no matter what. The question at hand concerns the process for editing and creating new configs and templates and how those changes will be tested. 

>how hard is it to add additional configs to the available options?

It won't be difficult, all of it can be done in the github UI. The potential tricky step the might be needed is creating a pull request to pull changes into a production branch once the editor is satisfied with the edits -- I'm still mulling this over, but I'm thinking this might not be necessary.

It's less clear though for templates -- templates require more time to create and more testing and tweaking, and it's more likely that people will need to switch between testing an experimental template and running g2h with a stable production template. 

For example, say a website is getting a redesign and the appearance of timetables needs to change, so the websites team works on a new template and needs to be able to use gtfs-to-html-service to test it out. While that redesign is in progress, the agency has a schedule update and needs to update timetables with their _old_ template. The goal is that we don't have to manually revert back to an older version of the template to do this.

I'm gonna mull on this a bit more, in the meantime these are the goals I want to keep in mind when it comes to managing assets and deploying them to gtfs-to-html-service servers:
- No one should need to have a local install of g2h to either create timetables, _or_ for creating and testing configs and templates
- Updating configs should be easy to do on-the-fly
- Ideally, people should be able to test changes to assets in a testing gtfs-to-html-service environment without necessarily needing to deploy those changes to production gtfs-to-html-service/GTFSM

**Comment by evantrillium** [comment]
@anniekfifer we won't be touching templates - that's far outside the scope of support

for configs, the support team won't be able to do edits to these, whether on staging or prod, with any simplicity. I would prefer to have a menu of available configs defined, with no need to do small tweaks.

I understand that there may be instances where the available menu of configs does not suit the website, and @ekeaton can always run g2h locally with modified configs, but we won't be able to support edits to configs on web-based gh at this time.  This also ensures we don't run into issues where multiple edits are happening simultaneously (unlikely, buit possible) and doesn't require edits be undone after the mods have been used.

My desire is to only have 4-5 total available configs (and ditch default and pvvta) so that a tech, using instructions from their export receipts, can select one of the available configs

**Comment by anniekfifer** [comment]
>@anniekfifer we won't be touching templates - that's far outside the scope of support

For sure, I meant to direct that to @ekeaton 

> we won't be able to support edits to configs on web-based gh at this time.

That's good to know! @ekeaton lmk if that changes things

**Comment by ekeaton** [comment]
@anniekfifer I'm on board with Support not being able to make edits to the configs within the GH UI but instead choosing from a list of 4-5 ready-to-go configs. For my example regarding `showStopCity`: false, to `showStopCity`: true as a reason they might need to edit a config before, instead that could just fall under its own config i.e. config-a. And any website that needs that option Support can just use that ready-to-go config no tweaks are needed. Makes sense to me!

 

> It's less clear though for templates -- templates require more time to create and more testing and tweaking, and it's more likely that people will need to switch between testing an experimental template and running g2h with a stable production template.

I will say we never create new templates for new websites. We only use the Trillium template and I've tweaked it beyond the default version to fit 99% of our websites. So we should be good to go there we won't need to update those on the fly or much. The only case will be when Brendan updates g2h with any major changes (generally he also changes up the template files) meaning we will need to test and then update ours accordingly. But I believe you solved this situation by coming up with testing branches!

**Comment by anniekfifer** [comment]
@ekeaton Thank you so much for your help with this! It sounds like just having the working branch deployed to gtfstohtml is the way to go. We can always beef up the branching process later if its needed for testing.

Thanks for being patient with the back-and-forth, let me know if this sounds alright!

### Timetables branches
- `main` 
  - main working branch
  - Deployed to [staging-gtfstohtml](staging-gtfstohtml.trilliumtransit.com) and [gtfstohtml](gtfstohtml.trilliumtransit.com)
    - Users can test changes to configs and templates on either site almost* immediately (*currently updates assets every 5 minutes or can be manually triggered to update production gtfstohtml using this [jenkins task](https://regression-testing.trilliumtransit.com/view/gtfstohtml/job/deploy_timetables_to_gtfstohtml/))
- Experimental version branches (i.e. `2.x` or `1.6.4`)
  - created for testing g2h tool version updates, will ultimately be pulled into `main` once it has been tested with the proper g2h version
 
### [G2H tool](https://github.com/BlinkTagInc/gtfs-to-html) version upgrade process
- Websites team creates a new versioned branch for assets in timetables repo
  - The branch might be identical to `main` but it's ideal to test on a separate branch so any needed changes can be tested without additional steps.
- Websites notifies gtfs-to-html-service developer of the branch name and desired g2h version to test with
- gtfs-to-html-service developer upgrades g2h in a new versioned branch and deploys to staging with versioned timetables branch
- Websites team tests on [staging-gtfstohtml](staging-gtfstohtml.trilliumtransit.com), and lets gtfs-to-html-service developer know if any changes are needed in the application or if everything works ok. 
- When staging gtfs-to-html-service is confirmed to be working with the new assets, the gtfs-to-html-service developer performs an upgrade (these things should all happen at the same time):
  - gtfs-to-html-service: version branch is pulled into `master`
  - timetables: version branch is pulled into `main`
  - Production gtfs-to-html-service is upgraded with updated code and assets
  - Version branches can be removed at this point, or kept for future use or reference if helpful

**Comment by ekeaton** [comment]
@anniekfifer This all sounds good to me! 😁

I think the only step we have left (unrelated to the processes you mentioned above) is the configs that @evantrillium would like his team to use. I know he has it on his docket to work on them so after that, we should be able to start using this wonderful new addition for our timetable process oh so soon. Thank you, thank you for all of your hard work!!

**Comment by anniekfifer** [comment]
Thanks @ekeaton ! I've added the info above to the [timetables](https://github.com/Trillium-Solutions/timetables) README.
